var searchData=
[
  ['unaryfunctor_0',['UnaryFunctor',['../structtesting_1_1gmock__more__actions__test_1_1_unary_functor.html',1,'testing::gmock_more_actions_test']]],
  ['unarymoveonlyfunctor_1',['UnaryMoveOnlyFunctor',['../structtesting_1_1gmock__more__actions__test_1_1_unary_move_only_functor.html',1,'testing::gmock_more_actions_test']]],
  ['undefined_20references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_2',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_include_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['underlying_20library_20support_20features_3',['Underlying library support features',['../md_include_2googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md386',1,'']]],
  ['underscore_4',['Why should test suite names and test names not contain underscore?',['../md_include_2googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['understanding_20uninteresting_20vs_20unexpected_20calls_5',['Understanding Uninteresting vs Unexpected Calls',['../md_include_2googletest_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'']]],
  ['undo_6',['undo',['../class_graw_editor.html#a64bfed5cb2b9d3fd6d2078c65da645ff',1,'GrawEditor']]],
  ['unexpected_20calls_7',['Unexpected Calls',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md143',1,'Disallowing Unexpected Calls'],['../md_include_2googletest_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'Understanding Uninteresting vs Unexpected Calls']]],
  ['uninteresting_20arguments_8',['Ignoring Uninteresting Arguments',['../md_include_2googletest_2docs_2gmock__cook__book.html#ParameterlessExpectations',1,'']]],
  ['uninteresting_20calls_9',['Uninteresting Calls',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md142',1,'Ignoring Uninteresting Calls'],['../md_include_2googletest_2docs_2gmock__for__dummies.html#autotoc_md212',1,'Uninteresting Calls']]],
  ['uninteresting_20function_20call_20encountered_20default_20action_20taken_20should_20i_20panic_10',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['uninteresting_20vs_20unexpected_20calls_11',['Understanding Uninteresting vs Unexpected Calls',['../md_include_2googletest_2docs_2gmock__cook__book.html#uninteresting-vs-unexpected',1,'']]],
  ['unittest_12',['UnitTest',['../classtesting_1_1_unit_test.html',1,'testing::UnitTest'],['../md_include_2googletest_2docs_2reference_2testing.html#UnitTest',1,'UnitTest']]],
  ['unittest_3a_3aad_5fhoc_5ftest_5fresult_13',['ad_hoc_test_result {#UnitTest::ad_hoc_test_result}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md331',1,'']]],
  ['unittest_3a_3acurrent_5ftest_5finfo_14',['current_test_info {#UnitTest::current_test_info}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md312',1,'']]],
  ['unittest_3a_3acurrent_5ftest_5fsuite_15',['current_test_suite {#UnitTest::current_test_suite}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md311',1,'']]],
  ['unittest_3a_3adisabled_5ftest_5fcount_16',['disabled_test_count {#UnitTest::disabled_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md322',1,'']]],
  ['unittest_3a_3aelapsed_5ftime_17',['elapsed_time {#UnitTest::elapsed_time}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md327',1,'']]],
  ['unittest_3a_3afailed_18',['Failed {#UnitTest::Failed}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md329',1,'']]],
  ['unittest_3a_3afailed_5ftest_5fcount_19',['failed_test_count {#UnitTest::failed_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md320',1,'']]],
  ['unittest_3a_3afailed_5ftest_5fsuite_5fcount_20',['failed_test_suite_count {#UnitTest::failed_test_suite_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md315',1,'']]],
  ['unittest_3a_3agetinstance_21',['GetInstance {#UnitTest::GetInstance}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md309',1,'']]],
  ['unittest_3a_3agettestsuite_22',['GetTestSuite {#UnitTest::GetTestSuite}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md330',1,'']]],
  ['unittest_3a_3alisteners_23',['listeners {#UnitTest::listeners}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md332',1,'']]],
  ['unittest_3a_3aoriginal_5fworking_5fdir_24',['original_working_dir {#UnitTest::original_working_dir}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md310',1,'']]],
  ['unittest_3a_3apassed_25',['Passed {#UnitTest::Passed}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md328',1,'']]],
  ['unittest_3a_3arandom_5fseed_26',['random_seed {#UnitTest::random_seed}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md313',1,'']]],
  ['unittest_3a_3areportable_5fdisabled_5ftest_5fcount_27',['reportable_disabled_test_count {#UnitTest::reportable_disabled_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md321',1,'']]],
  ['unittest_3a_3areportable_5ftest_5fcount_28',['reportable_test_count {#UnitTest::reportable_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md323',1,'']]],
  ['unittest_3a_3askipped_5ftest_5fcount_29',['skipped_test_count {#UnitTest::skipped_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md319',1,'']]],
  ['unittest_3a_3astart_5ftimestamp_30',['start_timestamp {#UnitTest::start_timestamp}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md326',1,'']]],
  ['unittest_3a_3asuccessful_5ftest_5fcount_31',['successful_test_count {#UnitTest::successful_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md318',1,'']]],
  ['unittest_3a_3asuccessful_5ftest_5fsuite_5fcount_32',['successful_test_suite_count {#UnitTest::successful_test_suite_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md314',1,'']]],
  ['unittest_3a_3atest_5fsuite_5fto_5frun_5fcount_33',['test_suite_to_run_count {#UnitTest::test_suite_to_run_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md317',1,'']]],
  ['unittest_3a_3atest_5fto_5frun_5fcount_34',['test_to_run_count {#UnitTest::test_to_run_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md325',1,'']]],
  ['unittest_3a_3atotal_5ftest_5fcount_35',['total_test_count {#UnitTest::total_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md324',1,'']]],
  ['unittest_3a_3atotal_5ftest_5fsuite_5fcount_36',['total_test_suite_count {#UnitTest::total_test_suite_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md316',1,'']]],
  ['unittesthelper_37',['UnitTestHelper',['../classtesting_1_1internal_1_1_unit_test_helper.html',1,'testing::internal']]],
  ['unittestimpl_38',['UnitTestImpl',['../classtesting_1_1internal_1_1_unit_test_impl.html',1,'testing::internal']]],
  ['unittestoptions_39',['UnitTestOptions',['../classtesting_1_1internal_1_1_unit_test_options.html',1,'testing::internal']]],
  ['unittestrecordpropertytesthelper_40',['UnitTestRecordPropertyTestHelper',['../classtesting_1_1internal_1_1_unit_test_record_property_test_helper.html',1,'testing::internal']]],
  ['universalprinter_41',['UniversalPrinter',['../classtesting_1_1internal_1_1_universal_printer.html',1,'testing::internal']]],
  ['universalprinter_3c_20const_20t_20_3e_42',['UniversalPrinter&lt; const T &gt;',['../classtesting_1_1internal_1_1_universal_printer_3_01const_01_t_01_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_20_26_20_3e_43',['UniversalPrinter&lt; T &amp; &gt;',['../classtesting_1_1internal_1_1_universal_printer_3_01_t_01_6_01_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_5bn_5d_3e_44',['UniversalPrinter&lt; T[N]&gt;',['../classtesting_1_1internal_1_1_universal_printer_3_01_t_0f_n_0e_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20wrapper_3c_20t_20_3e_20_3e_45',['UniversalPrinter&lt; Wrapper&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1_universal_printer_3_01_wrapper_3_01_t_01_4_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_46',['UniversalTersePrinter',['../classtesting_1_1internal_1_1_universal_terse_printer.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char_20_2a_20_3e_47',['UniversalTersePrinter&lt; char * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01char_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char16_5ft_20_2a_20_3e_48',['UniversalTersePrinter&lt; char16_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01char16__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char32_5ft_20_2a_20_3e_49',['UniversalTersePrinter&lt; char32_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01char32__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char_20_2a_20_3e_50',['UniversalTersePrinter&lt; const char * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char16_5ft_20_2a_20_3e_51',['UniversalTersePrinter&lt; const char16_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char16__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char32_5ft_20_2a_20_3e_52',['UniversalTersePrinter&lt; const char32_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char32__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20std_3a_3areference_5fwrapper_3c_20t_20_3e_20_3e_53',['UniversalTersePrinter&lt; std::reference_wrapper&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01std_1_1reference__wrapper_3_01_t_01_4_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20t_20_26_20_3e_54',['UniversalTersePrinter&lt; T &amp; &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_01_6_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20t_5bn_5d_3e_55',['UniversalTersePrinter&lt; T[N]&gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_0f_n_0e_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20wchar_5ft_20_2a_20_3e_56',['UniversalTersePrinter&lt; wchar_t * &gt;',['../classtesting_1_1internal_1_1_universal_terse_printer_3_01wchar__t_01_5_01_4.html',1,'testing::internal']]],
  ['unless_20said_20otherwise_57',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_include_2googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['unprintableinfoo_58',['UnprintableInFoo',['../classfoo_1_1_unprintable_in_foo.html',1,'foo']]],
  ['unprintabletemplateinglobal_59',['UnprintableTemplateInGlobal',['../class_unprintable_template_in_global.html',1,'']]],
  ['unprotected_20commas_60',['Dealing with unprotected commas',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md119',1,'']]],
  ['unstreamable_61',['Unstreamable',['../class_unstreamable.html',1,'']]],
  ['up_20a_20bazel_20workspace_62',['Set up a Bazel workspace',['../md_include_2googletest_2docs_2quickstart-bazel.html#autotoc_md231',1,'']]],
  ['up_20a_20project_63',['Set up a project',['../md_include_2googletest_2docs_2quickstart-cmake.html#autotoc_md236',1,'']]],
  ['up_20and_20tear_20down_64',['Global Set-Up and Tear-Down',['../md_include_2googletest_2docs_2advanced.html#autotoc_md44',1,'']]],
  ['updates_65',['Documentation Updates',['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md403',1,'']]],
  ['upon_20first_20failure_66',['Stop test execution upon first failure',['../md_include_2googletest_2docs_2advanced.html#autotoc_md63',1,'']]],
  ['use_20an_20assertion_20what_20gives_67',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_include_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['use_20invoke_20or_20implement_20the_20actioninterface_20interface_68',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['use_20move_20only_20types_69',['Mocking Methods That Use Move-Only Types',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md159',1,'']]],
  ['use_20setargpointee_20in_20willonce_20but_20gcc_20complains_20about_20conflicting_20return_20type_20specified_20what_20does_20it_20mean_70',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['use_20the_20constructor_20destructor_20of_20the_20test_20fixture_20or_20setup_20teardown_71',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_include_2googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['use_20tt_20assert_5fpred_20tt_20how_20do_20i_20fix_20it_72',['The compiler complains &quot;no matching function to call&quot; when I use &lt;tt&gt;ASSERT_PRED*&lt;/tt&gt;. How do I fix it?',['../md_include_2googletest_2docs_2faq.html#autotoc_md92',1,'']]],
  ['use_20typed_20tests_20or_20value_20parameterized_20tests_73',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_include_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['useful_20mocks_20created_20using_20gmock_74',['Useful Mocks Created Using gMock',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md178',1,'']]],
  ['user_20s_20guide_75',['GoogleTest User&apos;s Guide',['../md_include_2googletest_2docs_2index.html',1,'']]],
  ['userconstructortag_76',['UserConstructorTag',['../structtesting_1_1internal_1_1_do_all_action_3_01_final_action_01_4_1_1_user_constructor_tag.html',1,'testing::internal::DoAllAction&lt; FinalAction &gt;::UserConstructorTag'],['../structtesting_1_1internal_1_1_do_all_action_3_01_initial_action_00_01_other_actions_8_8_8_01_4_1_1_user_constructor_tag.html',1,'testing::internal::DoAllAction&lt; InitialAction, OtherActions... &gt;::UserConstructorTag']]],
  ['uses_20tt_20assert_5fdeath_20tt_77',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_include_2googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['using_20a_20function_20functor_20or_20lambda_20as_20an_20action_78',['Using a Function, Functor, or Lambda as an Action',['../md_include_2googletest_2docs_2reference_2actions.html#autotoc_md242',1,'']]],
  ['using_20a_20function_20that_20returns_20an_20assertionresult_79',['Using a Function That Returns an AssertionResult',['../md_include_2googletest_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['using_20a_20mock_20object_20but_20using_20a_20real_20object_20is_20fine_20what_20can_20be_20wrong_80',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['using_20a_20predicate_20formatter_81',['Using a Predicate-Formatter',['../md_include_2googletest_2docs_2advanced.html#autotoc_md18',1,'']]],
  ['using_20actions_82',['Using Actions',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md145',1,'']]],
  ['using_20an_20existing_20boolean_20function_83',['Using an Existing Boolean Function',['../md_include_2googletest_2docs_2advanced.html#autotoc_md16',1,'']]],
  ['using_20assertions_20in_20sub_20routines_84',['Using Assertions in Sub-routines',['../md_include_2googletest_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['using_20checkpoints_85',['Using Checkpoints',['../md_include_2googletest_2docs_2gmock__cook__book.html#UsingCheckPoints',1,'']]],
  ['using_20event_20listeners_86',['Using Event Listeners',['../md_include_2googletest_2docs_2advanced.html#autotoc_md57',1,'']]],
  ['using_20functions_20methods_20functors_20lambdas_20as_20actions_87',['Using Functions/Methods/Functors/Lambdas as Actions',['../md_include_2googletest_2docs_2gmock__cook__book.html#FunctionsAsActions',1,'']]],
  ['using_20functions_20with_20extra_20info_20as_20actions_88',['Using Functions with Extra Info as Actions',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md151',1,'']]],
  ['using_20gmock_89',['Using gMock',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md158',1,'Misc Recipes on Using gMock'],['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md178',1,'Useful Mocks Created Using gMock']]],
  ['using_20gmock_20and_20threads_90',['Using gMock and Threads',['../md_include_2googletest_2docs_2gmock__cook__book.html#UsingThreads',1,'']]],
  ['using_20gmock_20matchers_91',['Asserting Using gMock Matchers',['../md_include_2googletest_2docs_2advanced.html#autotoc_md21',1,'']]],
  ['using_20googletest_92',['Who Is Using GoogleTest?',['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md411',1,'']]],
  ['using_20googletest_20from_20various_20build_20systems_93',['Using GoogleTest from various build systems',['../md_include_2googletest_2docs_2pkgconfig.html',1,'']]],
  ['using_20matchers_94',['Using Matchers',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md128',1,'']]],
  ['using_20matchers_20as_20predicates_95',['Using Matchers as Predicates',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md133',1,'Using Matchers as Predicates'],['../md_include_2googletest_2docs_2reference_2matchers.html#MatchersAsPredicatesCheat',1,'Using Matchers as Predicates']]],
  ['using_20matchers_20in_20googletest_20assertions_96',['Using Matchers in googletest Assertions',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md134',1,'']]],
  ['using_20mocks_20in_20tests_97',['Using Mocks in Tests',['../md_include_2googletest_2docs_2gmock__cheat__sheet.html#UsingMocks',1,'Using Mocks in Tests'],['../md_include_2googletest_2docs_2gmock__for__dummies.html#autotoc_md206',1,'Using Mocks in Tests']]],
  ['using_20multiple_20expectations_98',['Using Multiple Expectations',['../md_include_2googletest_2docs_2gmock__for__dummies.html#MultiExpectations',1,'']]],
  ['using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_99',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['using_20pkg_20config_20in_20a_20cross_20compilation_20setting_100',['Using pkg-config in a cross-compilation setting',['../md_include_2googletest_2docs_2pkgconfig.html#autotoc_md218',1,'']]],
  ['using_20predicates_20as_20matchers_101',['Using Predicates as Matchers',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md135',1,'']]],
  ['using_20simple_20matchers_102',['Using Simple Matchers',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['using_20the_20action_20object_20s_20type_103',['Using the ACTION Object&apos;s Type',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md176',1,'']]],
  ['using_20the_20same_20data_20configuration_20for_20multiple_20tests_104',['Test Fixtures: Using the Same Data Configuration for Multiple Tests',['../md_include_2googletest_2docs_2primer.html#same-data-multiple-tests',1,'']]],
  ['utf_208_20text_20output_105',['Suppressing UTF-8 Text Output',['../md_include_2googletest_2docs_2advanced.html#autotoc_md73',1,'']]]
];
