var searchData=
[
  ['random_0',['Random',['../classtesting_1_1internal_1_1_random.html',1,'testing::internal']]],
  ['random_5fseed_20unittest_3a_3arandom_5fseed_1',['random_seed {#UnitTest::random_seed}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md313',1,'']]],
  ['rangegenerator_2',['RangeGenerator',['../classtesting_1_1internal_1_1_range_generator.html',1,'testing::internal']]],
  ['rawbytesprinter_3',['RawBytesPrinter',['../structtesting_1_1internal_1_1_raw_bytes_printer.html',1,'testing::internal']]],
  ['real_20object_4',['Delegating Calls to a Real Object',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md126',1,'']]],
  ['real_20object_20is_20fine_20what_20can_20be_20wrong_5',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_6',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md180',1,'']]],
  ['reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_7',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['recipes_20on_20using_20gmock_8',['Misc Recipes on Using gMock',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md158',1,'']]],
  ['recordproperty_20test_3a_3arecordproperty_9',['RecordProperty {#Test::RecordProperty}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md279',1,'']]],
  ['rectangle_10',['Rectangle',['../class_rectangle.html',1,'']]],
  ['redo_11',['redo',['../class_graw_editor.html#a93569e4d97cf2c683ec06c697cbaa129',1,'GrawEditor']]],
  ['redundant_12',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md186',1,'']]],
  ['reference_13',['Reference',['../md_include_2googletest_2docs_2reference_2actions.html',1,'Actions Reference'],['../md_include_2googletest_2docs_2reference_2assertions.html',1,'Assertions Reference'],['../md_include_2googletest_2docs_2reference_2matchers.html',1,'Matchers Reference'],['../md_include_2googletest_2docs_2reference_2mocking.html',1,'Mocking Reference'],['../md_include_2googletest_2docs_2reference_2testing.html',1,'Testing Reference']]],
  ['references_20from_20mock_20methods_14',['Returning References from Mock Methods',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md146',1,'']]],
  ['references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_15',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_include_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['register_5ftyped_5ftest_5fsuite_5fp_16',['REGISTER_TYPED_TEST_SUITE_P',['../md_include_2googletest_2docs_2reference_2testing.html#REGISTER_TYPED_TEST_SUITE_P',1,'']]],
  ['registering_20tests_20programmatically_17',['Registering tests programmatically',['../md_include_2googletest_2docs_2advanced.html#autotoc_md53',1,'']]],
  ['registertest_18',['RegisterTest',['../md_include_2googletest_2docs_2reference_2testing.html#RegisterTest',1,'']]],
  ['regular_20expression_20syntax_19',['Regular Expression Syntax',['../md_include_2googletest_2docs_2advanced.html#autotoc_md31',1,'']]],
  ['related_20macros_3a_20',['Flag related macros:',['../md_include_2googletest_2googlemock_2include_2gmock_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md376',1,'']]],
  ['related_20open_20source_20projects_21',['Related Open Source Projects',['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md412',1,'']]],
  ['relationtosourcecopy_22',['RelationToSourceCopy',['../structtesting_1_1internal_1_1_relation_to_source_copy.html',1,'testing::internal']]],
  ['relationtosourcereference_23',['RelationToSourceReference',['../structtesting_1_1internal_1_1_relation_to_source_reference.html',1,'testing::internal']]],
  ['release_201_2014_200_24',['Release 1.14.0',['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md404',1,'']]],
  ['release_20testeventlisteners_3a_3arelease_25',['Release {#TestEventListeners::Release}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md347',1,'']]],
  ['remove_26',['remove',['../class_graw_editor.html#aae8db8b911524798f60df3852bffecef',1,'GrawEditor']]],
  ['removeconstfromkey_27',['RemoveConstFromKey',['../structtesting_1_1internal_1_1_remove_const_from_key.html',1,'testing::internal']]],
  ['removeconstfromkey_3c_20std_3a_3apair_3c_20const_20k_2c_20v_20_3e_20_3e_28',['RemoveConstFromKey&lt; std::pair&lt; const K, V &gt; &gt;',['../structtesting_1_1internal_1_1_remove_const_from_key_3_01std_1_1pair_3_01const_01_k_00_01_v_01_4_01_4.html',1,'testing::internal']]],
  ['removelocations_29',['RemoveLocations',['../namespacegmock__output__test.html#a59c40167b074a2ef04aecc79a0273f13',1,'gmock_output_test']]],
  ['removememoryaddresses_30',['RemoveMemoryAddresses',['../namespacegmock__output__test.html#ac16c3c4b4875becf250dd73beb381a82',1,'gmock_output_test']]],
  ['removereportheaderandfooter_31',['RemoveReportHeaderAndFooter',['../namespacegmock__output__test.html#acb06643e5e0d0eb85a3bc067e09e56f9',1,'gmock_output_test']]],
  ['removetestnamesofleakedmocks_32',['RemoveTestNamesOfLeakedMocks',['../namespacegmock__output__test.html#ad0a9e9474fb8cb1729c20bc51222c46e',1,'gmock_output_test']]],
  ['repeating_20the_20tests_33',['Repeating the Tests',['../md_include_2googletest_2docs_2advanced.html#autotoc_md66',1,'']]],
  ['report_34',['Report',['../md_include_2googletest_2docs_2advanced.html#autotoc_md75',1,'Generating a JSON Report'],['../md_include_2googletest_2docs_2advanced.html#autotoc_md74',1,'Generating an XML Report']]],
  ['reportable_5fdisabled_5ftest_5fcount_20testsuite_3a_3areportable_5fdisabled_5ftest_5fcount_35',['reportable_disabled_test_count {#TestSuite::reportable_disabled_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md288',1,'']]],
  ['reportable_5fdisabled_5ftest_5fcount_20unittest_3a_3areportable_5fdisabled_5ftest_5fcount_36',['reportable_disabled_test_count {#UnitTest::reportable_disabled_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md321',1,'']]],
  ['reportable_5ftest_5fcount_20testsuite_3a_3areportable_5ftest_5fcount_37',['reportable_test_count {#TestSuite::reportable_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md290',1,'']]],
  ['reportable_5ftest_5fcount_20unittest_3a_3areportable_5ftest_5fcount_38',['reportable_test_count {#UnitTest::reportable_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md323',1,'']]],
  ['reported_39',['Controlling How Failures Are Reported',['../md_include_2googletest_2docs_2advanced.html#autotoc_md76',1,'']]],
  ['require_20the_20entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20tt_20deathtest_20tt_20when_20it_20uses_20tt_20assert_5fdeath_20tt_40',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_include_2googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['requirements_20for_20contributors_41',['Requirements for Contributors',['../md_include_2googletest_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md7',1,'']]],
  ['requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_42',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_include_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['reset_43',['reset',['../class_graw_editor.html#a2bda0d9746440420ca1bc732c81573f2',1,'GrawEditor']]],
  ['resetting_20a_20mock_44',['Verifying and Resetting a Mock',['../md_include_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md114',1,'']]],
  ['resize_45',['resize',['../class_graw_editor.html#ae448c08b6275bc7844a64d3ebb3d4654',1,'GrawEditor']]],
  ['resources_20between_20tests_20in_20the_20same_20test_20suite_46',['Sharing Resources Between Tests in the Same Test Suite',['../md_include_2googletest_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['restricting_20the_20type_20of_20an_20argument_20or_20parameter_20in_20an_20action_47',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md174',1,'']]],
  ['result_48',['Ignoring an Action&apos;s Result',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md154',1,'']]],
  ['result_20of_20a_20function_20functor_20or_20callback_49',['Matching the Result of a Function, Functor, or Callback',['../md_include_2googletest_2docs_2reference_2matchers.html#autotoc_md253',1,'']]],
  ['result_20testinfo_3a_3aresult_50',['result {#TestInfo::result}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md308',1,'']]],
  ['retires_51',['Controlling When an Expectation Retires',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md144',1,'']]],
  ['retiresonsaturation_20expect_5fcall_20retiresonsaturation_52',['RetiresOnSaturation {#EXPECT_CALL.RetiresOnSaturation}',['../md_include_2googletest_2docs_2reference_2mocking.html#autotoc_md265',1,'']]],
  ['return_20a_20value_20what_20s_20going_20on_53',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_include_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['return_20type_54',['Setting the Default Value for a Return Type',['../md_include_2googletest_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['return_20type_20specified_20what_20does_20it_20mean_55',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['return_20value_20when_20i_20call_20run_5fall_5ftests_20why_56',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_include_2googletest_2docs_2faq.html#autotoc_md93',1,'']]],
  ['returnaction_57',['ReturnAction',['../classtesting_1_1internal_1_1_return_action.html',1,'testing::internal']]],
  ['returnaction_3c_20bymovewrapper_3c_20t_20_3e_20_3e_58',['ReturnAction&lt; ByMoveWrapper&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1_return_action_3_01_by_move_wrapper_3_01_t_01_4_01_4.html',1,'testing::internal']]],
  ['returnargaction_59',['ReturnArgAction',['../structtesting_1_1internal_1_1_return_arg_action.html',1,'testing::internal']]],
  ['returning_20a_20value_60',['Returning a Value',['../md_include_2googletest_2docs_2reference_2actions.html#autotoc_md240',1,'']]],
  ['returning_20live_20values_20from_20mock_20methods_61',['Returning Live Values from Mock Methods',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['returning_20references_20from_20mock_20methods_62',['Returning References from Mock Methods',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md146',1,'']]],
  ['returnnewaction_63',['ReturnNewAction',['../structtesting_1_1internal_1_1_return_new_action.html',1,'testing::internal']]],
  ['returnnullaction_64',['ReturnNullAction',['../classtesting_1_1internal_1_1_return_null_action.html',1,'testing::internal']]],
  ['returnpointeeaction_65',['ReturnPointeeAction',['../structtesting_1_1internal_1_1_return_pointee_action.html',1,'testing::internal']]],
  ['returnrefaction_66',['ReturnRefAction',['../classtesting_1_1internal_1_1_return_ref_action.html',1,'testing::internal']]],
  ['returnrefofcopyaction_67',['ReturnRefOfCopyAction',['../classtesting_1_1internal_1_1_return_ref_of_copy_action.html',1,'testing::internal']]],
  ['returnroundrobinaction_68',['ReturnRoundRobinAction',['../classtesting_1_1internal_1_1_return_round_robin_action.html',1,'testing::internal']]],
  ['returns_20an_20assertionresult_69',['Using a Function That Returns an AssertionResult',['../md_include_2googletest_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['returnvoidaction_70',['ReturnVoidAction',['../classtesting_1_1internal_1_1_return_void_action.html',1,'testing::internal']]],
  ['routines_71',['Using Assertions in Sub-routines',['../md_include_2googletest_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['rsquo_20when_20i_20use_20an_20assertion_20what_20gives_72',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_include_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_73',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['run_20a_20binary_74',['Run a binary',['../md_include_2googletest_2docs_2quickstart-bazel.html#autotoc_md232',1,'Create and run a binary'],['../md_include_2googletest_2docs_2quickstart-cmake.html#autotoc_md237',1,'Create and run a binary']]],
  ['run_5fall_5ftests_75',['RUN_ALL_TESTS',['../md_include_2googletest_2docs_2reference_2testing.html#RUN_ALL_TESTS',1,'']]],
  ['run_5fall_5ftests_20why_76',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_include_2googletest_2docs_2faq.html#autotoc_md93',1,'']]],
  ['run_5fwith_5fflag_77',['run_with_flag',['../namespacegtest__help__test.html#a3bc360e67ea70e1a210d608bdffbd3de',1,'gtest_help_test']]],
  ['runandverify_78',['RunAndVerify',['../classgoogletest-break-on-failure-unittest_1_1_g_test_break_on_failure_unit_test.html#aa10728830adf68f6c0fd9e8ff9a3e5a2',1,'googletest-break-on-failure-unittest.GTestBreakOnFailureUnitTest.RunAndVerify()'],['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a210d536f4dd4dc5d8ea687747ca8d6d5',1,'googletest-filter-unittest.GTestFilterUnitTest.RunAndVerify()'],['../classgoogletest-list-tests-unittest_1_1_g_test_list_tests_unit_test.html#a181f8f8424ac864380a56f443bd571e7',1,'googletest-list-tests-unittest.GTestListTestsUnitTest.RunAndVerify()'],['../classgoogletest-throw-on-failure-test_1_1_throw_on_failure_test.html#a4438abd96792c91b81e3bae28fc27087',1,'googletest-throw-on-failure-test.ThrowOnFailureTest.RunAndVerify()']]],
  ['runandverifyallowingdisabled_79',['RunAndVerifyAllowingDisabled',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a8ec218a765232f76b13c81f17c8ee11f',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['runandverifywithsharding_80',['RunAndVerifyWithSharding',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a8c4225edcc9ca56e44976fa0d7d84d0b',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['running_20a_20subset_20of_20the_20tests_81',['Running a Subset of the Tests',['../md_include_2googletest_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['running_20in_20a_20test_82',['How can my code detect if it is running in a test?',['../md_include_2googletest_2docs_2faq.html#autotoc_md107',1,'']]],
  ['running_20test_20programs_3a_20advanced_20options_83',['Running Test Programs: Advanced Options',['../md_include_2googletest_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['running_20tests_20in_20emacs_84',['Running Tests in Emacs',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md165',1,'']]],
  ['runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_85',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['runtimes_86',['Visual Studio Dynamic vs Static Runtimes',['../md_include_2googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md394',1,'']]]
];
