var searchData=
[
  ['s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_0',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['s_20argument_1',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['s_20argument_20in_20an_20action_2',['How can I delete the mock function&apos;s argument in an action?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['s_20arguments_3',['Selecting an Action&apos;s Arguments',['../md_include_2googletest_2docs_2gmock__cook__book.html#SelectingArgs',1,'']]],
  ['s_20behavior_20based_20on_20the_20state_4',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md149',1,'']]],
  ['s_20c_20test_20framework_5',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md407',1,'']]],
  ['s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_6',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_include_2googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['s_20going_20on_7',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_include_2googletest_2docs_2faq.html#autotoc_md94',1,'']]],
  ['s_20guide_8',['GoogleTest User&apos;s Guide',['../md_include_2googletest_2docs_2index.html',1,'']]],
  ['s_20name_9',['Getting the Current Test&apos;s Name',['../md_include_2googletest_2docs_2advanced.html#autotoc_md54',1,'']]],
  ['s_20result_10',['Ignoring an Action&apos;s Result',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md154',1,'']]],
  ['s_20the_20problem_11',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md180',1,'']]],
  ['s_20type_12',['Using the ACTION Object&apos;s Type',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md176',1,'']]],
  ['s_20wrong_13',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_include_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['said_20otherwise_14',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_include_2googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['same_20data_20configuration_20for_20multiple_20tests_15',['Test Fixtures: Using the Same Data Configuration for Multiple Tests',['../md_include_2googletest_2docs_2primer.html#same-data-multiple-tests',1,'']]],
  ['same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_16',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_include_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['same_20test_20suite_17',['Sharing Resources Between Tests in the Same Test Suite',['../md_include_2googletest_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['samples_18',['Googletest Samples',['../md_include_2googletest_2docs_2samples.html',1,'']]],
  ['sanitizer_20integration_19',['Sanitizer Integration',['../md_include_2googletest_2docs_2advanced.html#autotoc_md80',1,'']]],
  ['satisfied_20isn_20t_20this_20redundant_20',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md186',1,'']]],
  ['satisfied_20what_20should_20i_20do_21',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md183',1,'']]],
  ['satisfy_20some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_22',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_include_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['saveargaction_23',['SaveArgAction',['../structtesting_1_1internal_1_1_save_arg_action.html',1,'testing::internal']]],
  ['saveargpointeeaction_24',['SaveArgPointeeAction',['../structtesting_1_1internal_1_1_save_arg_pointee_action.html',1,'testing::internal']]],
  ['scoped_5ftrace_25',['SCOPED_TRACE',['../md_include_2googletest_2docs_2reference_2testing.html#SCOPED_TRACE',1,'']]],
  ['scopedmocklog_20tt_20spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_26',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md184',1,'']]],
  ['scopedtrace_27',['ScopedTrace',['../classtesting_1_1_scoped_trace.html',1,'testing::ScopedTrace'],['../md_include_2googletest_2docs_2reference_2testing.html#ScopedTrace',1,'ScopedTrace']]],
  ['secret_28',['Secret',['../classtesting_1_1internal_1_1_secret.html',1,'testing::internal']]],
  ['see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_29',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_include_2googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['seems_20lost_20after_20the_20death_20test_20finishes_20why_30',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_include_2googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['seems_20pretty_20tedious_31',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_include_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['seg_20faults_20how_20do_20i_20fix_20it_32',['My death test hangs (or seg-faults). How do I fix it?',['../md_include_2googletest_2docs_2faq.html#autotoc_md91',1,'']]],
  ['select_33',['select',['../class_graw_editor.html#af0baeb44411f6ddd57d33e661de41695',1,'GrawEditor']]],
  ['selecting_20an_20action_20s_20arguments_34',['Selecting an Action&apos;s Arguments',['../md_include_2googletest_2docs_2gmock__cook__book.html#SelectingArgs',1,'']]],
  ['selecting_20between_20overloaded_20functions_35',['Selecting Between Overloaded Functions',['../md_include_2googletest_2docs_2gmock__cook__book.html#SelectOverload',1,'']]],
  ['selecting_20tests_36',['Selecting Tests',['../md_include_2googletest_2docs_2advanced.html#autotoc_md60',1,'']]],
  ['separate_20tt_20test_20foo_20bar_20tt_20test_20methods_20defined_20in_20different_20namespaces_37',['Is it OK if I have two separate &lt;tt&gt;TEST(Foo, Bar)&lt;/tt&gt; test methods defined in different namespaces?',['../md_include_2googletest_2docs_2faq.html#autotoc_md109',1,'']]],
  ['separateinstancetest_38',['SeparateInstanceTest',['../class_separate_instance_test.html',1,'']]],
  ['sequence_39',['Sequence',['../md_include_2googletest_2docs_2reference_2mocking.html#Sequence',1,'']]],
  ['sequencetestinglistener_40',['SequenceTestingListener',['../class_sequence_testing_listener.html',1,'']]],
  ['set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_41',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['set_20up_20a_20bazel_20workspace_42',['Set up a Bazel workspace',['../md_include_2googletest_2docs_2quickstart-bazel.html#autotoc_md231',1,'']]],
  ['set_20up_20a_20project_43',['Set up a project',['../md_include_2googletest_2docs_2quickstart-cmake.html#autotoc_md236',1,'']]],
  ['set_20up_20and_20tear_20down_44',['Global Set-Up and Tear-Down',['../md_include_2googletest_2docs_2advanced.html#autotoc_md44',1,'']]],
  ['setargpointee_20in_20willonce_20but_20gcc_20complains_20about_20conflicting_20return_20type_20specified_20what_20does_20it_20mean_45',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['setargrefereeaction_46',['SetArgRefereeAction',['../structtesting_1_1internal_1_1_set_arg_referee_action.html',1,'testing::internal']]],
  ['setargumentpointeeaction_47',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1_set_argument_pointee_action.html',1,'testing::internal']]],
  ['setarrayargumentaction_48',['SetArrayArgumentAction',['../structtesting_1_1internal_1_1_set_array_argument_action.html',1,'testing::internal']]],
  ['setenvvar_49',['SetEnvVar',['../namespacegtest__test__utils.html#abece99ff6c6b9c882ab12c15793898bf',1,'gtest_test_utils']]],
  ['seterrnoandreturnaction_50',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1_set_errno_and_return_action.html',1,'testing::internal']]],
  ['setting_51',['Using pkg-config in a cross-compilation setting',['../md_include_2googletest_2docs_2pkgconfig.html#autotoc_md218',1,'']]],
  ['setting_20default_20actions_52',['Setting Default Actions',['../md_include_2googletest_2docs_2gmock__cheat__sheet.html#OnCall',1,'']]],
  ['setting_20expectations_53',['Setting Expectations',['../md_include_2googletest_2docs_2gmock__cheat__sheet.html#ExpectCall',1,'Setting Expectations'],['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md141',1,'Setting Expectations'],['../md_include_2googletest_2docs_2gmock__for__dummies.html#autotoc_md207',1,'Setting Expectations']]],
  ['setting_20the_20default_20actions_20for_20a_20mock_20method_54',['Setting the Default Actions for a Mock Method',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md150',1,'']]],
  ['setting_20the_20default_20value_20for_20a_20return_20type_55',['Setting the Default Value for a Return Type',['../md_include_2googletest_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['setup_56',['setUp',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a80e82b6c777fbbf575ad83cb8d2ae56c',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['setup_57',['Setup',['../md_include_2googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md390',1,'']]],
  ['setup_20environment_3a_3asetup_58',['SetUp {#Environment::SetUp}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md271',1,'']]],
  ['setup_20function_20is_20not_20called_20why_59',['My SetUp() function is not called. Why?',['../md_include_2googletest_2docs_2faq.html#autotoc_md95',1,'']]],
  ['setup_20teardown_60',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_include_2googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['setup_20test_3a_3asetup_61',['SetUp {#Test::SetUp}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md280',1,'']]],
  ['setupenvironment_62',['SetupEnvironment',['../class_setup_environment.html',1,'']]],
  ['setupfailtest_63',['SetupFailTest',['../class_setup_fail_test.html',1,'']]],
  ['setuptestcasetest_64',['SetUpTestCaseTest',['../classtesting_1_1_set_up_test_case_test.html',1,'testing']]],
  ['setuptestsuite_20test_3a_3asetuptestsuite_65',['SetUpTestSuite {#Test::SetUpTestSuite}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md273',1,'']]],
  ['setuptestsuitetest_66',['SetUpTestSuiteTest',['../classtesting_1_1_set_up_test_suite_test.html',1,'testing']]],
  ['setvalue_67',['SetValue',['../md_include_2googletest_2docs_2reference_2testing.html#SetValue',1,'']]],
  ['several_20test_20suites_20which_20share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_68',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_include_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['shape_69',['Shape',['../class_shape.html',1,'Shape'],['../class_shape.html#a52d12da45e055d91bb02310195a3e88d',1,'Shape::Shape()']]],
  ['shapetypetostring_70',['ShapeTypeToString',['../class_graw_editor.html#a2d0d39fdcc6c665aa3ee0c30395e46b4',1,'GrawEditor']]],
  ['share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_71',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_include_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['shared_20library_20dll_72',['As a Shared Library (DLL)',['../md_include_2googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md398',1,'']]],
  ['sharing_20actions_73',['Sharing Actions',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md156',1,'']]],
  ['sharing_20matchers_74',['Sharing Matchers',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md140',1,'']]],
  ['sharing_20resources_20between_20tests_20in_20the_20same_20test_20suite_75',['Sharing Resources Between Tests in the Same Test Suite',['../md_include_2googletest_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['sheet_76',['gMock Cheat Sheet',['../md_include_2googletest_2docs_2gmock__cheat__sheet.html',1,'']]],
  ['should_20i_20do_77',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md183',1,'']]],
  ['should_20i_20panic_78',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['should_20i_20prefer_20test_20fixtures_20over_20global_20variables_79',['Why should I prefer test fixtures over global variables?',['../md_include_2googletest_2docs_2faq.html#autotoc_md98',1,'']]],
  ['should_20i_20use_20invoke_20or_20implement_20the_20actioninterface_20interface_80',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['should_20i_20use_20the_20constructor_20destructor_20of_20the_20test_20fixture_20or_20setup_20teardown_81',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_include_2googletest_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_82',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_include_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['should_20it_20do_83',['Actions: What Should It Do?',['../md_include_2googletest_2docs_2gmock__for__dummies.html#autotoc_md211',1,'']]],
  ['should_20test_20suite_20names_20and_20test_20names_20not_20contain_20underscore_84',['Why should test suite names and test names not contain underscore?',['../md_include_2googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['should_5frun_20testinfo_3a_3ashould_5frun_85',['should_run {#TestInfo::should_run}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md306',1,'']]],
  ['should_5frun_20testsuite_3a_3ashould_5frun_86',['should_run {#TestSuite::should_run}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md284',1,'']]],
  ['show_20the_20warning_20in_20this_20case_87',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['shuffling_20the_20tests_88',['Shuffling the Tests',['../md_include_2googletest_2docs_2advanced.html#autotoc_md67',1,'']]],
  ['side_20effects_89',['Matchers must have no side-effects',['../md_include_2googletest_2docs_2gmock__cook__book.html#PureMatchers',1,'']]],
  ['side_20effects_90',['Side Effects',['../md_include_2googletest_2docs_2gmock__cook__book.html#MockingSideEffects',1,'Mocking Side Effects'],['../md_include_2googletest_2docs_2reference_2actions.html#autotoc_md241',1,'Side Effects']]],
  ['simple_20matchers_91',['Using Simple Matchers',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['simple_20tests_92',['Simple Tests',['../md_include_2googletest_2docs_2primer.html#autotoc_md225',1,'']]],
  ['simplifying_20the_20interface_20without_20breaking_20existing_20code_93',['Simplifying the Interface without Breaking Existing Code',['../md_include_2googletest_2docs_2gmock__cook__book.html#SimplerInterfaces',1,'']]],
  ['skipentireenvironmenttest_94',['SkipEntireEnvironmentTest',['../classgtest__skip__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_check_output_test.SkipEntireEnvironmentTest'],['../classgtest__skip__environment__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_environment_check_output_test.SkipEntireEnvironmentTest']]],
  ['skipped_20testpartresult_3a_3askipped_95',['skipped {#TestPartResult::skipped}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md355',1,'']]],
  ['skipped_20testresult_3a_3askipped_96',['Skipped {#TestResult::Skipped}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md363',1,'']]],
  ['skipped_5ftest_5fcount_20testsuite_3a_3askipped_5ftest_5fcount_97',['skipped_test_count {#TestSuite::skipped_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md286',1,'']]],
  ['skipped_5ftest_5fcount_20unittest_3a_3askipped_5ftest_5fcount_98',['skipped_test_count {#UnitTest::skipped_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md319',1,'']]],
  ['skippedtest_99',['SkippedTest',['../class_skipped_test.html',1,'']]],
  ['skipping_20test_20execution_100',['Skipping test execution',['../md_include_2googletest_2docs_2advanced.html#autotoc_md26',1,'']]],
  ['some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_101',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_include_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['some_20state_20but_20the_20change_20seems_20lost_20after_20the_20death_20test_20finishes_20why_102',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_include_2googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_103',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_include_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['soon_104',['Coming Soon',['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md406',1,'']]],
  ['source_20projects_105',['Related Open Source Projects',['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md412',1,'']]],
  ['specified_20what_20does_20it_20mean_106',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['specify_20the_20actions_20gmock_20sucks_107',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['specifying_20calling_20conventions_20for_20mock_20functions_108',['Specifying Calling Conventions for Mock Functions',['../md_include_2googletest_2docs_2gmock__cheat__sheet.html#autotoc_md112',1,'']]],
  ['specifying_20names_20for_20value_20parameterized_20test_20parameters_109',['Specifying Names for Value-Parameterized Test Parameters',['../md_include_2googletest_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_110',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md184',1,'']]],
  ['stackinterface_111',['StackInterface',['../classtesting_1_1gmock__function__mocker__test_1_1_stack_interface.html',1,'testing::gmock_function_mocker_test']]],
  ['standalone_20cmake_20project_112',['Standalone CMake Project',['../md_include_2googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md392',1,'']]],
  ['standard_20version_113',['C++ Standard Version',['../md_include_2googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md395',1,'']]],
  ['start_5ftimestamp_20testresult_3a_3astart_5ftimestamp_114',['start_timestamp {#TestResult::start_timestamp}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md368',1,'']]],
  ['start_5ftimestamp_20testsuite_3a_3astart_5ftimestamp_115',['start_timestamp {#TestSuite::start_timestamp}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md296',1,'']]],
  ['start_5ftimestamp_20unittest_3a_3astart_5ftimestamp_116',['start_timestamp {#UnitTest::start_timestamp}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md326',1,'']]],
  ['started_117',['Started',['../md_include_2googletest_2docs_2gmock__for__dummies.html#autotoc_md201',1,'Getting Started'],['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md408',1,'Getting Started']]],
  ['state_118',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md149',1,'']]],
  ['state_20but_20the_20change_20seems_20lost_20after_20the_20death_20test_20finishes_20why_119',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_include_2googletest_2docs_2faq.html#autotoc_md86',1,'']]],
  ['statefulnamingfunctor_120',['StatefulNamingFunctor',['../struct_stateful_naming_functor.html',1,'']]],
  ['statefulnamingtest_121',['StatefulNamingTest',['../class_stateful_naming_test.html',1,'']]],
  ['statement_20argument_20in_20assert_5fdeath_20be_122',['What can the statement argument in ASSERT_DEATH() be?',['../md_include_2googletest_2docs_2faq.html#autotoc_md99',1,'']]],
  ['static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_123',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_include_2googletest_2docs_2faq.html#autotoc_md88',1,'']]],
  ['static_20global_20function_20can_20i_20mock_20it_124',['My code calls a static/global function. Can I mock it?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['static_20runtimes_125',['Visual Studio Dynamic vs Static Runtimes',['../md_include_2googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md394',1,'']]],
  ['staticasserttypeeq_126',['StaticAssertTypeEq',['../md_include_2googletest_2docs_2reference_2testing.html#StaticAssertTypeEq',1,'']]],
  ['staticasserttypeeqtesthelper_127',['StaticAssertTypeEqTestHelper',['../class_static_assert_type_eq_test_helper.html',1,'']]],
  ['std_3a_3afunction_128',['Mock std::function',['../md_include_2googletest_2docs_2gmock__cook__book.html#MockFunction',1,'']]],
  ['steps_129',['Steps',['../md_include_2googletest_2docs_2quickstart-bazel.html#autotoc_md233',1,'Next steps'],['../md_include_2googletest_2docs_2quickstart-cmake.html#autotoc_md238',1,'Next steps']]],
  ['sticky_20unless_20said_20otherwise_130',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_include_2googletest_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['stlcontainerview_131',['StlContainerView',['../classtesting_1_1internal_1_1_stl_container_view.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_132',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_1_1std_1_1tuple_3_01_element_pointer_00_01_size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_133',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_element_0f_n_0e_4.html',1,'testing::internal']]],
  ['stop_20test_20execution_20upon_20first_20failure_134',['Stop test execution upon first failure',['../md_include_2googletest_2docs_2advanced.html#autotoc_md63',1,'']]],
  ['streamableinglobal_135',['StreamableInGlobal',['../class_streamable_in_global.html',1,'']]],
  ['streamableinlocal_136',['StreamableInLocal',['../structfoo_1_1_streamable_in_local.html',1,'foo']]],
  ['streamabletemplateinfoo_137',['StreamableTemplateInFoo',['../classfoo_1_1_streamable_template_in_foo.html',1,'foo']]],
  ['streamprinter_138',['StreamPrinter',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1_stream_printer.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['strict_20and_20the_20naggy_139',['The Nice, the Strict, and the Naggy',['../md_include_2googletest_2docs_2gmock__cook__book.html#NiceStrictNaggy',1,'']]],
  ['strictmock_140',['StrictMock',['../classtesting_1_1_strict_mock.html',1,'testing::StrictMock&lt; MockClass &gt;'],['../md_include_2googletest_2docs_2reference_2mocking.html#StrictMock',1,'StrictMock']]],
  ['strictmockimpl_141',['StrictMockImpl',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mockclass_20_3e_142',['StrictMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['string_143',['String',['../classtesting_1_1internal_1_1_string.html',1,'testing::internal']]],
  ['string_20assertions_144',['More String Assertions',['../md_include_2googletest_2docs_2advanced.html#autotoc_md22',1,'']]],
  ['string_20comparison_145',['String Comparison',['../md_include_2googletest_2docs_2reference_2assertions.html#c-strings',1,'']]],
  ['string_20matchers_146',['String Matchers',['../md_include_2googletest_2docs_2reference_2matchers.html#autotoc_md250',1,'']]],
  ['strong_20googletest_20strong_20google_20s_20c_20test_20framework_147',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md407',1,'']]],
  ['studio_20dynamic_20vs_20static_20runtimes_148',['Visual Studio Dynamic vs Static Runtimes',['../md_include_2googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md394',1,'']]],
  ['stuff_20it_20s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_149',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['style_150',['Style',['../md_include_2googletest_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md6',1,'']]],
  ['style_20tt_20mock_5fmethodn_20tt_20macros_151',['Old-Style &lt;tt&gt;MOCK_METHODn&lt;/tt&gt; Macros',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md124',1,'']]],
  ['styles_152',['Death Test Styles',['../md_include_2googletest_2docs_2advanced.html#autotoc_md34',1,'']]],
  ['sub_20routines_153',['Using Assertions in Sub-routines',['../md_include_2googletest_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['submit_20your_20own_20code_154',['How to become a contributor and submit your own code',['../md_include_2googletest_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['subprocess_155',['Subprocess',['../classgtest__test__utils_1_1_subprocess.html',1,'gtest_test_utils']]],
  ['subroutines_156',['Asserting on Subroutines',['../md_include_2googletest_2docs_2advanced.html#autotoc_md40',1,'']]],
  ['subroutines_20with_20an_20exception_157',['Asserting on Subroutines with an exception',['../md_include_2googletest_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['subset_20of_20the_20tests_158',['Running a Subset of the Tests',['../md_include_2googletest_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['succeed_159',['SUCCEED',['../md_include_2googletest_2docs_2reference_2assertions.html#SUCCEED',1,'']]],
  ['succeeds_160',['GoogleTest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_include_2googletest_2docs_2faq.html#autotoc_md104',1,'']]],
  ['success_20and_20failure_161',['Success and Failure',['../md_include_2googletest_2docs_2advanced.html#autotoc_md13',1,'Explicit Success and Failure'],['../md_include_2googletest_2docs_2reference_2assertions.html#success-failure',1,'Explicit Success and Failure']]],
  ['successful_5ftest_5fcount_20testsuite_3a_3asuccessful_5ftest_5fcount_162',['successful_test_count {#TestSuite::successful_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md285',1,'']]],
  ['successful_5ftest_5fcount_20unittest_3a_3asuccessful_5ftest_5fcount_163',['successful_test_count {#UnitTest::successful_test_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md318',1,'']]],
  ['successful_5ftest_5fsuite_5fcount_20unittest_3a_3asuccessful_5ftest_5fsuite_5fcount_164',['successful_test_suite_count {#UnitTest::successful_test_suite_count}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md314',1,'']]],
  ['successfultest_165',['SuccessfulTest',['../class_successful_test.html',1,'']]],
  ['sucks_166',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['suite_167',['Sharing Resources Between Tests in the Same Test Suite',['../md_include_2googletest_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['suite_20instead_20of_20individual_20tests_20to_20be_20named_20tt_20deathtest_20tt_20when_20it_20uses_20tt_20assert_5fdeath_20tt_168',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_include_2googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['suite_20names_20and_20test_20names_20not_20contain_20underscore_169',['Why should test suite names and test names not contain underscore?',['../md_include_2googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['suite_20tt_20deathtest_20tt_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_170',['But I don&apos;t like calling my entire test suite &lt;tt&gt;*DeathTest&lt;/tt&gt; when it contains both death tests and non-death tests. What do I do?',['../md_include_2googletest_2docs_2faq.html#autotoc_md103',1,'']]],
  ['suiteapiresolver_171',['SuiteApiResolver',['../structtesting_1_1internal_1_1_suite_api_resolver.html',1,'testing::internal']]],
  ['suites_20which_20share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_172',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_include_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['summary_20testpartresult_3a_3asummary_173',['summary {#TestPartResult::summary}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md353',1,'']]],
  ['sumof5functor_174',['SumOf5Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of5_functor.html',1,'testing::gmock_more_actions_test']]],
  ['sumof6functor_175',['SumOf6Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of6_functor.html',1,'testing::gmock_more_actions_test']]],
  ['super_20vision_20into_20mock_20calls_176',['Gaining Super Vision into Mock Calls',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md164',1,'']]],
  ['support_20features_177',['Underlying library support features',['../md_include_2googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md386',1,'']]],
  ['support_20tt_20expect_5feq_20null_20ptr_20tt_20and_20tt_20assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_178',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_include_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['supported_20platforms_179',['Supported Platforms',['../md_include_2googletest_2docs_2platforms.html',1,'Supported Platforms'],['../md_include_2googletest_2_r_e_a_d_m_e.html#autotoc_md410',1,'Supported Platforms']]],
  ['suppress_20the_20memory_20leak_20messages_20on_20windows_180',['How do I suppress the memory leak messages on Windows?',['../md_include_2googletest_2docs_2faq.html#autotoc_md106',1,'']]],
  ['suppressing_20test_20passes_181',['Suppressing test passes',['../md_include_2googletest_2docs_2advanced.html#autotoc_md71',1,'']]],
  ['suppressing_20the_20elapsed_20time_182',['Suppressing the Elapsed Time',['../md_include_2googletest_2docs_2advanced.html#autotoc_md72',1,'']]],
  ['suppressing_20utf_208_20text_20output_183',['Suppressing UTF-8 Text Output',['../md_include_2googletest_2docs_2advanced.html#autotoc_md73',1,'']]],
  ['symbols_3a_184',['Exporting API symbols:',['../md_include_2googletest_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md387',1,'']]],
  ['syntax_185',['Syntax',['../md_include_2googletest_2docs_2gmock__for__dummies.html#autotoc_md208',1,'General Syntax'],['../md_include_2googletest_2docs_2advanced.html#autotoc_md31',1,'Regular Expression Syntax']]],
  ['systems_186',['Using GoogleTest from various build systems',['../md_include_2googletest_2docs_2pkgconfig.html',1,'']]]
];
