var searchData=
[
  ['naggy_0',['The Nice, the Strict, and the Naggy',['../md_include_2googletest_2docs_2gmock__cook__book.html#NiceStrictNaggy',1,'']]],
  ['naggymock_1',['NaggyMock',['../classtesting_1_1_naggy_mock.html',1,'testing::NaggyMock&lt; MockClass &gt;'],['../md_include_2googletest_2docs_2reference_2mocking.html#NaggyMock',1,'NaggyMock']]],
  ['naggymock_3c_20mockfoo_20_3e_2',['NaggyMock&lt; MockFoo &gt;',['../classtesting_1_1_naggy_mock.html',1,'testing']]],
  ['naggymockimpl_3',['NaggyMockImpl',['../classtesting_1_1internal_1_1_naggy_mock_impl.html',1,'testing::internal']]],
  ['naggymockimpl_3c_20mockclass_20_3e_4',['NaggyMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1_naggy_mock_impl.html',1,'testing::internal']]],
  ['naggymockimpl_3c_20mockfoo_20_3e_5',['NaggyMockImpl&lt; MockFoo &gt;',['../classtesting_1_1internal_1_1_naggy_mock_impl.html',1,'testing::internal']]],
  ['name_6',['Getting the Current Test&apos;s Name',['../md_include_2googletest_2docs_2advanced.html#autotoc_md54',1,'']]],
  ['name_20clashes_7',['Avoiding Macro Name Clashes',['../md_include_2googletest_2googletest_2_r_e_a_d_m_e.html#autotoc_md399',1,'']]],
  ['name_20testinfo_3a_3aname_8',['name {#TestInfo::name}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md300',1,'']]],
  ['name_20testsuite_3a_3aname_9',['name {#TestSuite::name}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md282',1,'']]],
  ['named_20tt_20deathtest_20tt_20when_20it_20uses_20tt_20assert_5fdeath_20tt_10',['Why does GoogleTest require the entire test suite, instead of individual tests, to be named &lt;tt&gt;*DeathTest&lt;/tt&gt; when it uses &lt;tt&gt;ASSERT_DEATH&lt;/tt&gt;?',['../md_include_2googletest_2docs_2faq.html#autotoc_md102',1,'']]],
  ['namegeneratorselector_11',['NameGeneratorSelector',['../structtesting_1_1internal_1_1_name_generator_selector.html',1,'testing::internal']]],
  ['names_12',['Listing Test Names',['../md_include_2googletest_2docs_2advanced.html#autotoc_md61',1,'']]],
  ['names_20and_20test_20names_20not_20contain_20underscore_13',['Why should test suite names and test names not contain underscore?',['../md_include_2googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['names_20for_20value_20parameterized_20test_20parameters_14',['Specifying Names for Value-Parameterized Test Parameters',['../md_include_2googletest_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['namespaces_15',['Is it OK if I have two separate &lt;tt&gt;TEST(Foo, Bar)&lt;/tt&gt; test methods defined in different namespaces?',['../md_include_2googletest_2docs_2faq.html#autotoc_md109',1,'']]],
  ['naming_16',['Death Test Naming',['../md_include_2googletest_2docs_2advanced.html#autotoc_md30',1,'']]],
  ['namingtest_17',['NamingTest',['../class_naming_test.html',1,'']]],
  ['nativearray_18',['NativeArray',['../classtesting_1_1internal_1_1_native_array.html',1,'testing::internal']]],
  ['need_20to_20test_20that_20different_20implementations_20of_20an_20interface_20satisfy_20some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_19',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_include_2googletest_2docs_2faq.html#autotoc_md85',1,'']]],
  ['needs_20to_20do_20complex_20stuff_20it_20s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_20',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['negation_21',['negation',['../structtesting_1_1internal_1_1negation.html',1,'testing::internal']]],
  ['never_20called_22',['How can I assert that a function is NEVER called?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['new_20action_20templates_20quickly_23',['Writing New Action Templates Quickly',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md175',1,'']]],
  ['new_20actions_24',['Writing New Actions',['../md_include_2googletest_2docs_2gmock__cook__book.html#QuickNewActions',1,'']]],
  ['new_20cardinalities_25',['Writing New Cardinalities',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md171',1,'']]],
  ['new_20matchers_20quickly_26',['Writing New Matchers Quickly',['../md_include_2googletest_2docs_2gmock__cook__book.html#NewMatchers',1,'']]],
  ['new_20monomorphic_20actions_27',['Writing New Monomorphic Actions',['../md_include_2googletest_2docs_2gmock__cook__book.html#NewMonoActions',1,'']]],
  ['new_20monomorphic_20matchers_28',['Writing New Monomorphic Matchers',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md168',1,'']]],
  ['new_20parameterized_20matchers_20quickly_29',['Writing New Parameterized Matchers Quickly',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md167',1,'']]],
  ['new_20polymorphic_20actions_30',['Writing New Polymorphic Actions',['../md_include_2googletest_2docs_2gmock__cook__book.html#NewPolyActions',1,'']]],
  ['new_20polymorphic_20matchers_31',['Writing New Polymorphic Matchers',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md169',1,'']]],
  ['new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_32',['I have several test suites which share the same test fixture logic; do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_include_2googletest_2docs_2faq.html#autotoc_md96',1,'']]],
  ['newer_20expectations_20override_20older_20ones_20rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_33',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['next_20steps_34',['Next steps',['../md_include_2googletest_2docs_2quickstart-bazel.html#autotoc_md233',1,'Next steps'],['../md_include_2googletest_2docs_2quickstart-cmake.html#autotoc_md238',1,'Next steps']]],
  ['nice_20the_20strict_20and_20the_20naggy_35',['The Nice, the Strict, and the Naggy',['../md_include_2googletest_2docs_2gmock__cook__book.html#NiceStrictNaggy',1,'']]],
  ['nicemock_36',['NiceMock',['../classtesting_1_1_nice_mock.html',1,'testing::NiceMock&lt; MockClass &gt;'],['../md_include_2googletest_2docs_2reference_2mocking.html#NiceMock',1,'NiceMock']]],
  ['nicemockimpl_37',['NiceMockImpl',['../classtesting_1_1internal_1_1_nice_mock_impl.html',1,'testing::internal']]],
  ['nicemockimpl_3c_20mockclass_20_3e_38',['NiceMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1_nice_mock_impl.html',1,'testing::internal']]],
  ['no_20match_20for_20operator_20rsquo_20when_20i_20use_20an_20assertion_20what_20gives_39',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_include_2googletest_2docs_2faq.html#autotoc_md105',1,'']]],
  ['no_20matching_20function_20for_20call_20to_20footest_3a_3afootest_20tt_20why_40',['I have a fixture class &lt;tt&gt;FooTest&lt;/tt&gt;, but &lt;tt&gt;TEST_F(FooTest, Bar)&lt;/tt&gt; gives me error &lt;tt&gt;&quot;no matching function for call to `FooTest::FooTest()&apos;&quot;&lt;/tt&gt;. Why?',['../md_include_2googletest_2docs_2faq.html#autotoc_md100',1,'']]],
  ['no_20matching_20function_20to_20call_20when_20i_20use_20tt_20assert_5fpred_20tt_20how_20do_20i_20fix_20it_41',['The compiler complains &quot;no matching function to call&quot; when I use &lt;tt&gt;ASSERT_PRED*&lt;/tt&gt;. How do I fix it?',['../md_include_2googletest_2docs_2faq.html#autotoc_md92',1,'']]],
  ['no_20side_20effects_42',['Matchers must have no side-effects',['../md_include_2googletest_2docs_2gmock__cook__book.html#PureMatchers',1,'']]],
  ['nodefaultconstructor_43',['NoDefaultConstructor',['../classtesting_1_1internal_1_1_no_default_constructor.html',1,'testing::internal']]],
  ['nomenclature_44',['Beware of the Nomenclature',['../md_include_2googletest_2docs_2primer.html#autotoc_md222',1,'']]],
  ['non_20death_20tests_20what_20do_20i_20do_45',['But I don&apos;t like calling my entire test suite &lt;tt&gt;*DeathTest&lt;/tt&gt; when it contains both death tests and non-death tests. What do I do?',['../md_include_2googletest_2docs_2faq.html#autotoc_md103',1,'']]],
  ['non_20virtual_20methods_46',['Mocking Non-virtual Methods',['../md_include_2googletest_2docs_2gmock__cook__book.html#MockingNonVirtualMethods',1,'']]],
  ['noncontainer_47',['NonContainer',['../class_non_container.html',1,'']]],
  ['nondefaultconstructassignstring_48',['NonDefaultConstructAssignString',['../class_non_default_construct_assign_string.html',1,'']]],
  ['none_49',['None',['../structtesting_1_1internal_1_1_none.html',1,'testing::internal']]],
  ['nonfatalfailureinfixtureconstructortest_50',['NonFatalFailureInFixtureConstructorTest',['../class_non_fatal_failure_in_fixture_constructor_test.html',1,'']]],
  ['nonfatalfailureinsetuptest_51',['NonFatalFailureInSetUpTest',['../class_non_fatal_failure_in_set_up_test.html',1,'']]],
  ['nonfatally_5ffailed_20testpartresult_3a_3anonfatally_5ffailed_52',['nonfatally_failed {#TestPartResult::nonfatally_failed}',['../md_include_2googletest_2docs_2reference_2testing.html#autotoc_md357',1,'']]],
  ['nonparameterizedbasetest_53',['NonParameterizedBaseTest',['../class_non_parameterized_base_test.html',1,'']]],
  ['normal_20class_54',['Mocking a Normal Class',['../md_include_2googletest_2docs_2gmock__cheat__sheet.html#MockClass',1,'']]],
  ['normalize_55',['normalize',['../namespacegtest__json__test__utils.html#ada57e0a99abb228db0fae7702c1d9bd8',1,'gtest_json_test_utils']]],
  ['normalizeerrormarker_56',['NormalizeErrorMarker',['../namespacegmock__output__test.html#aeeb22f52d3bf1ba7dbda8f8847faa103',1,'gmock_output_test']]],
  ['normalizexml_57',['NormalizeXml',['../classgtest__xml__test__utils_1_1_g_test_x_m_l_test_case.html#a2b8aed90eb732e3cc3f0cc333e19a2f0',1,'gtest_xml_test_utils::GTestXMLTestCase']]],
  ['not_20called_20why_58',['My SetUp() function is not called. Why?',['../md_include_2googletest_2docs_2faq.html#autotoc_md95',1,'']]],
  ['not_20contain_20underscore_59',['Why should test suite names and test names not contain underscore?',['../md_include_2googletest_2docs_2faq.html#autotoc_md83',1,'']]],
  ['not_20copyable_60',['Matching Arguments that Are Not Copyable',['../md_include_2googletest_2docs_2gmock__cook__book.html#autotoc_md136',1,'']]],
  ['not_20ignored_20as_20it_20ought_20to_20be_20what_20does_20this_20mean_61',['My compiler complains &quot;void value not ignored as it ought to be.&quot; What does this mean?',['../md_include_2googletest_2docs_2faq.html#autotoc_md90',1,'']]],
  ['not_20satisfied_20isn_20t_20this_20redundant_62',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md186',1,'']]],
  ['not_20satisfied_20what_20should_20i_20do_63',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md183',1,'']]],
  ['not_20to_20show_20the_20warning_20in_20this_20case_64',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_include_2googletest_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_65',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_include_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['notconstdebugstringmethod_66',['NotConstDebugStringMethod',['../struct_not_const_debug_string_method.html',1,'']]],
  ['notdefaultconstructible_67',['NotDefaultConstructible',['../classtesting_1_1gmock__nice__strict__test_1_1_not_default_constructible.html',1,'testing::gmock_nice_strict_test']]],
  ['notinstantiatedtest_68',['NotInstantiatedTest',['../classworks__here_1_1_not_instantiated_test.html',1,'works_here']]],
  ['notinstantiatedtypetest_69',['NotInstantiatedTypeTest',['../classworks__here_1_1_not_instantiated_type_test.html',1,'works_here']]],
  ['notreallyahashtable_70',['NotReallyAHashTable',['../struct_not_really_a_hash_table.html',1,'']]],
  ['notusedtest_71',['NotUsedTest',['../classworks__here_1_1_not_used_test.html',1,'works_here']]],
  ['notusedtypetest_72',['NotUsedTypeTest',['../classworks__here_1_1_not_used_type_test.html',1,'works_here']]],
  ['null_20ptr_20tt_20and_20tt_20assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_73',['Why does GoogleTest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_include_2googletest_2docs_2faq.html#autotoc_md84',1,'']]],
  ['numerictest_74',['NumericTest',['../classlibrary1_1_1_numeric_test.html',1,'library1::NumericTest&lt; T &gt;'],['../classlibrary2_1_1_numeric_test.html',1,'library2::NumericTest&lt; T &gt;']]]
];
